import com.mycompany.u2a2_edmondiiang.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author edmon
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbasePAra = new javax.swing.JTextField();
        lblheightPara = new javax.swing.JLabel();
        lblparallelogram = new javax.swing.JLabel();
        btnRemoveShape = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btnAddPrice = new javax.swing.JButton();
        txtlengthsquare = new javax.swing.JTextField();
        lbllengthSquare = new javax.swing.JLabel();
        txtpricesquare = new javax.swing.JTextField();
        lblcosttotal = new javax.swing.JLabel();
        lblpriceSquare = new javax.swing.JLabel();
        btncalculate = new javax.swing.JButton();
        lblsquare = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listshapes = new javax.swing.JList<>();
        lblhexagon = new javax.swing.JLabel();
        btnHexa = new javax.swing.JButton();
        btncircle = new javax.swing.JButton();
        txtlengthhex = new javax.swing.JTextField();
        lblrectangle = new javax.swing.JLabel();
        lbllengthHex = new javax.swing.JLabel();
        btnrectangle = new javax.swing.JButton();
        txtlengthofrect = new javax.swing.JTextField();
        lbllengthRec = new javax.swing.JLabel();
        txtpriceofrect = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtradiusofcir = new javax.swing.JTextField();
        lblcircle = new javax.swing.JLabel();
        lblradius = new javax.swing.JLabel();
        txtpriceofcir = new javax.swing.JTextField();
        lblpricecircle = new javax.swing.JLabel();
        lblfloorsize = new javax.swing.JLabel();
        txtfloorsize = new javax.swing.JTextField();
        txtpricehex = new javax.swing.JTextField();
        lblpriceHex = new javax.swing.JLabel();
        lblNote2 = new javax.swing.JLabel();
        lblpriceRec = new javax.swing.JLabel();
        txtwidthofrect = new javax.swing.JTextField();
        lblwidthRec = new javax.swing.JLabel();
        txtheightTri = new javax.swing.JTextField();
        lblheightTri = new javax.swing.JLabel();
        lbltriangle = new javax.swing.JLabel();
        brnrectangle = new javax.swing.JButton();
        txtbaseTri = new javax.swing.JTextField();
        lblbaseTri = new javax.swing.JLabel();
        txtpriceTri = new javax.swing.JTextField();
        lblpriceTri = new javax.swing.JLabel();
        btndonut = new javax.swing.JButton();
        txtoutradius = new javax.swing.JTextField();
        lblouterradius = new javax.swing.JLabel();
        txtpricedonut = new javax.swing.JTextField();
        lblpricedonut = new javax.swing.JLabel();
        txtInnradius = new javax.swing.JTextField();
        lblinnerradius = new javax.swing.JLabel();
        lbldonut = new javax.swing.JLabel();
        btnpara = new javax.swing.JButton();
        txtheightPara = new javax.swing.JTextField();
        lblbasepara = new javax.swing.JLabel();
        txtpricePara = new javax.swing.JTextField();
        lblpricepara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblheightPara.setText("Height:");

        lblparallelogram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblparallelogram.setText("Parallelogram:");

        btnRemoveShape.setText("Remove Shape");
        btnRemoveShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveShapeActionPerformed(evt);
            }
        });

        btnClearAll.setText("Clear All");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        btnAddPrice.setText("Add Square");
        btnAddPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPriceActionPerformed(evt);
            }
        });

        lbllengthSquare.setText("Length:");

        txtpricesquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpricesquareActionPerformed(evt);
            }
        });

        lblcosttotal.setText("Total Cost: ");

        lblpriceSquare.setText("Price:");

        btncalculate.setText("Calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        lblsquare.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsquare.setText("Square:");

        jScrollPane1.setViewportView(listshapes);

        lblhexagon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblhexagon.setText("Hexagon:");

        btnHexa.setText("Add Hexagon");
        btnHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexaActionPerformed(evt);
            }
        });

        btncircle.setText("Add Circle");
        btncircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncircleActionPerformed(evt);
            }
        });

        lblrectangle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblrectangle.setText("Rectangle:");

        lbllengthHex.setText("Length:");

        btnrectangle.setText("Add Rectangle");
        btnrectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrectangleActionPerformed(evt);
            }
        });

        lbllengthRec.setText("Length:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Edmond's Tile Shape Calculator");

        lblcircle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcircle.setText("Circle:");

        lblradius.setText("Radius:");

        lblpricecircle.setText("Price:");

        lblfloorsize.setText("Floor size:");

        lblpriceHex.setText("Price:");

        lblNote2.setText("floor size can be greater than 1 or small than 1");

        lblpriceRec.setText("Price:");

        lblwidthRec.setText("Width:");

        lblheightTri.setText("Height:");

        lbltriangle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbltriangle.setText("Triangle:");

        brnrectangle.setText("Add Triangle");
        brnrectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnrectangleActionPerformed(evt);
            }
        });

        lblbaseTri.setText("Base:");

        lblpriceTri.setText("Price:");

        btndonut.setText("Add Donut");
        btndonut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonutActionPerformed(evt);
            }
        });

        lblouterradius.setText("OuterRadius:");

        lblpricedonut.setText("Price:");

        lblinnerradius.setText("Inner Radius:");

        lbldonut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldonut.setText("Donut:");

        btnpara.setText("Add Parallelogram");
        btnpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparaActionPerformed(evt);
            }
        });

        lblbasepara.setText("Base:");

        lblpricepara.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblTitle)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblouterradius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtoutradius, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblinnerradius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtInnradius, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btndonut)
                                    .addComponent(lbldonut))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpricedonut, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpricedonut))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblhexagon)
                                    .addComponent(btnHexa)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbllengthHex, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblpriceHex))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtlengthhex, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtpricehex, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtheightTri, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblheightTri))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblbaseTri)
                                                    .addComponent(txtbaseTri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblpriceTri)
                                                    .addComponent(txtpriceTri, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(brnrectangle)
                                            .addComponent(lbltriangle))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAddPrice)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbllengthSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtlengthsquare, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtpricesquare, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblpriceSquare)))
                                            .addComponent(lblsquare))
                                        .addGap(62, 62, 62))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblrectangle)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtlengthofrect, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtwidthofrect, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnrectangle)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbllengthRec)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblwidthRec)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtpriceofrect, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblpriceRec))))
                                    .addComponent(btncircle)
                                    .addComponent(lblcircle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblradius)
                                            .addComponent(txtradiusofcir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(lblpricecircle))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtpriceofcir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(266, 266, 266)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblparallelogram)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbasePAra, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtheightPara, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblheightPara)
                                        .addGap(42, 42, 42)
                                        .addComponent(lblbasepara))
                                    .addComponent(btnpara)
                                    .addComponent(txtpricePara, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblpricepara))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(btnRemoveShape, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(66, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfloorsize, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncalculate))
                            .addComponent(lblfloorsize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcosttotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNote2)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcircle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblradius)
                            .addComponent(lblpricecircle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtradiusofcir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpriceofcir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncircle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbltriangle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblheightTri)
                                .addComponent(lblpriceTri)
                                .addComponent(lblbaseTri))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtheightTri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpriceTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbaseTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(brnrectangle))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblrectangle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbllengthRec)
                                                .addComponent(lblwidthRec))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtlengthofrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtwidthofrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtpriceofrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblpriceRec)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblparallelogram)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblheightPara)
                                        .addComponent(lblbasepara))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtbasePAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtheightPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnrectangle))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblpricepara))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbldonut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblouterradius)
                            .addComponent(lblinnerradius)
                            .addComponent(lblpricedonut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtoutradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInnradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpricedonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndonut))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpricePara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblhexagon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbllengthHex)
                                    .addComponent(lblpriceHex))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtlengthhex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpricehex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHexa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblsquare)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbllengthSquare)
                                    .addComponent(lblpriceSquare))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtlengthsquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpricesquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddPrice)
                                    .addComponent(btnRemoveShape)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnpara)
                                .addGap(27, 27, 27)
                                .addComponent(btnClearAll)
                                .addGap(29, 29, 29)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblfloorsize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfloorsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncalculate)
                            .addComponent(lblcosttotal)))
                    .addComponent(lblNote2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    List<shape> floorlistofshapes = new ArrayList();
    
    public boolean isDouble(String toCheck)
    {
        // Verify if the string is parsable. Return false if that isn't the case. Alternatively, return true

        
        try
        {
            double num = Double.parseDouble(toCheck);
            return true;
            
            
            
        }
        catch (Exception e)
        {
            
            return false;
        }
    }
    
    private void UpdateList()
    {
        DefaultListModel model = new DefaultListModel();
        listshapes.setModel(model);
        
        // Clear all the items 
        model.removeAllElements();
        
        // Move all item from the list into list box
        for(shape object : floorlistofshapes)
            
            
        {
            model.addElement(object.toString());
            
            
            
            System.out.println(object.name + " | " + object.cost + " | " + object.totalCost());
        }
    }
    private void btnRemoveShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveShapeActionPerformed
    shape toRemove = null;

        // loop scan the array of items
        // Locate the one that has to be deleted, then set it to be removed from that object.
        for(shape obj : floorlistofshapes)
        {
            // Get the ID of the selected item
            String[] selectedSplit = listshapes.getSelectedValue().split("|");
            int ID = Integer.parseInt(selectedSplit[0]);

            if(obj.id == ID)
            {
                toRemove = obj;
            }
        }

        floorlistofshapes.remove(toRemove); 
        // the object to remove

        UpdateList();
        //updates the list
    }//GEN-LAST:event_btnRemoveShapeActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        // Clear the array
        floorlistofshapes.clear();
        UpdateList();
        //updates the list
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void btnAddPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPriceActionPerformed
        try
        {
            // Create a new square object and add it to the list of shapes
            floorlistofshapes.add(new square(Double.parseDouble(txtlengthsquare.getText()), Double.parseDouble(txtpricesquare.getText()), listshapes.getModel().getSize())); // Add shape to the array

            UpdateList(); 
            // Update the list
        }
        catch(Exception e)
        {
            // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Triangle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddPriceActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        // Check if the floor size input is empty or not a valid double
        if(txtfloorsize.getText().isEmpty() || !isDouble(txtfloorsize.getText()))
        {
            // Display an error message and return if input is invalid
            JOptionPane.showMessageDialog(null, "Enter a valid total floor size", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Parse the total floor size from the input

        double totalFloorSize = Double.parseDouble(txtfloorsize.getText());
        
        // This is in m^2
        double sizeOfAllShapes = 0; 
        
        
        
        double totalCost = 0;

        // Calculate the total cost and size for each form in the list by looping through it.
        for(shape shape : floorlistofshapes)
        {
            totalCost += shape.totalCost();

            // Add the size to total as well
            sizeOfAllShapes += shape.getArea();
        }

        // Check if the floor is too small
        if(sizeOfAllShapes - 1 > totalFloorSize)
        {
            // Display an error message and return if the floor is too small
            JOptionPane.showMessageDialog(null, "The floor you have is too small! Please remove some tiles", "Error: floor too small", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if floor is too big
        if(sizeOfAllShapes < totalFloorSize - 1)
        {
            // Display an error message and return if there are not enough tiles
            JOptionPane.showMessageDialog(null, "You have not enough tiles! Please add some more tiles", "Error: Not enough tiles", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Round the cost to the nearest 5 because its money and we do not use the pennies
        totalCost = Math.round(totalCost * 100.0 / 5.0) * 5.0 / 100.0;
        
        // Update the label to display the total cost
        lblcosttotal.setText("Total Cost: $" + totalCost);
        //Number on the left in the list is an ID, it wont change no matter what
    }//GEN-LAST:event_btncalculateActionPerformed

    private void btnHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexaActionPerformed
        try
        {
            // Create a new hexagon object and add it to the list of shapes
            floorlistofshapes.add(new hexagon(Double.parseDouble(txtlengthhex.getText()), Double.parseDouble(txtpricehex.getText()), listshapes.getModel().getSize())); // Add shape to the array
            // Update the displayed list of shapes
            UpdateList(); 
        }
        catch(Exception e)
        {
            // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Triangle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHexaActionPerformed

    private void btncircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncircleActionPerformed
        try
        {
            // Create a new circle object and add it to the list of shapes
            floorlistofshapes.add(new Circle(Integer.parseInt(txtradiusofcir.getText()), Double.parseDouble(txtpriceofcir.getText()), listshapes.getModel().getSize())); // Add shape to the array
            // Update the displayed list of shapes
            UpdateList();
        }
        catch(Exception e)
        {
             // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Circle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btncircleActionPerformed

    private void btnrectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrectangleActionPerformed
        try
        {
            // Create a new rectangle object and add it to the list of shapes
            floorlistofshapes.add(new rectangle(Double.parseDouble(txtlengthofrect.getText()), Double.parseDouble(txtwidthofrect.getText()), Double.parseDouble(txtpriceofrect.getText()), listshapes.getModel().getSize())); // Add shape to the array
            
            // Update the displayed list of shapes
            UpdateList(); 
        }
        catch(Exception e)
        {
            // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Rectangle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnrectangleActionPerformed

    private void brnrectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnrectangleActionPerformed
        try
        {
            // Create a new triangle object and add it to the list of shapes
            floorlistofshapes.add(new triangle(Double.parseDouble(txtbaseTri.getText()), Double.parseDouble(txtheightTri.getText()), Double.parseDouble(txtpriceTri.getText()), listshapes.getModel().getSize())); // Add shape to the array

            // Update the displayed list of shapes
            UpdateList();
        }
        catch(Exception e)
        {
            // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Triangle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_brnrectangleActionPerformed

    private void btndonutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonutActionPerformed
        try
        {
            // Create a new donut object and add it to the list of shapes
            floorlistofshapes.add(new donut(Double.parseDouble(txtoutradius.getText()), Double.parseDouble(txtInnradius.getText()), Double.parseDouble(txtpricedonut.getText()), listshapes.getModel().getSize())); // Add shape to the array
 
            // Update the displayed list of shapes
            UpdateList(); 
        }
        catch(Exception e)
        {
            // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Triangle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btndonutActionPerformed

    private void btnparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparaActionPerformed
        try
        {           
            // Create a new parallelogram object and add it to the list of shapes
            floorlistofshapes.add(new parallelogram(Double.parseDouble(txtbasePAra.getText()), Double.parseDouble(txtheightPara.getText()), Double.parseDouble(txtpricePara.getText()), listshapes.getModel().getSize())); // Add shape to the array
            
            // Update the displayed list of shapes
            UpdateList(); 
        }
        catch(Exception e)
        {
            // Display an error message if there's an exception (e.g., incorrect input)
            JOptionPane.showMessageDialog(null, "Please make sure all info is entered correctly and is not empty", "Adding Triangle Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnparaActionPerformed

    private void txtpricesquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpricesquareActionPerformed
    }//GEN-LAST:event_txtpricesquareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnrectangle;
    private javax.swing.JButton btnAddPrice;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnHexa;
    private javax.swing.JButton btnRemoveShape;
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btncircle;
    private javax.swing.JButton btndonut;
    private javax.swing.JButton btnpara;
    private javax.swing.JButton btnrectangle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNote2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbaseTri;
    private javax.swing.JLabel lblbasepara;
    private javax.swing.JLabel lblcircle;
    private javax.swing.JLabel lblcosttotal;
    private javax.swing.JLabel lbldonut;
    private javax.swing.JLabel lblfloorsize;
    private javax.swing.JLabel lblheightPara;
    private javax.swing.JLabel lblheightTri;
    private javax.swing.JLabel lblhexagon;
    private javax.swing.JLabel lblinnerradius;
    private javax.swing.JLabel lbllengthHex;
    private javax.swing.JLabel lbllengthRec;
    private javax.swing.JLabel lbllengthSquare;
    private javax.swing.JLabel lblouterradius;
    private javax.swing.JLabel lblparallelogram;
    private javax.swing.JLabel lblpriceHex;
    private javax.swing.JLabel lblpriceRec;
    private javax.swing.JLabel lblpriceSquare;
    private javax.swing.JLabel lblpriceTri;
    private javax.swing.JLabel lblpricecircle;
    private javax.swing.JLabel lblpricedonut;
    private javax.swing.JLabel lblpricepara;
    private javax.swing.JLabel lblradius;
    private javax.swing.JLabel lblrectangle;
    private javax.swing.JLabel lblsquare;
    private javax.swing.JLabel lbltriangle;
    private javax.swing.JLabel lblwidthRec;
    private javax.swing.JList<String> listshapes;
    private javax.swing.JTextField txtInnradius;
    private javax.swing.JTextField txtbasePAra;
    private javax.swing.JTextField txtbaseTri;
    private javax.swing.JTextField txtfloorsize;
    private javax.swing.JTextField txtheightPara;
    private javax.swing.JTextField txtheightTri;
    private javax.swing.JTextField txtlengthhex;
    private javax.swing.JTextField txtlengthofrect;
    private javax.swing.JTextField txtlengthsquare;
    private javax.swing.JTextField txtoutradius;
    private javax.swing.JTextField txtpricePara;
    private javax.swing.JTextField txtpriceTri;
    private javax.swing.JTextField txtpricedonut;
    private javax.swing.JTextField txtpricehex;
    private javax.swing.JTextField txtpriceofcir;
    private javax.swing.JTextField txtpriceofrect;
    private javax.swing.JTextField txtpricesquare;
    private javax.swing.JTextField txtradiusofcir;
    private javax.swing.JTextField txtwidthofrect;
    // End of variables declaration//GEN-END:variables
}
